// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: userRpc.proto

package server

import (
	"context"

	"gozero_demo/userRpc/internal/logic"
	"gozero_demo/userRpc/internal/svc"
	"gozero_demo/userRpc/userRpc"
)

type UserRpcServer struct {
	svcCtx *svc.ServiceContext
	userRpc.UnimplementedUserRpcServer
}

func NewUserRpcServer(svcCtx *svc.ServiceContext) *UserRpcServer {
	return &UserRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UserRpcServer) Ping(ctx context.Context, in *userRpc.Request) (*userRpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
