// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: userRpc.proto

package userrpcclient

import (
	"context"

	"gozero_demo/userRpc/userRpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = userRpc.Request
	Response = userRpc.Response

	UserRpc interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultUserRpc struct {
		cli zrpc.Client
	}
)

func NewUserRpc(cli zrpc.Client) UserRpc {
	return &defaultUserRpc{
		cli: cli,
	}
}

func (m *defaultUserRpc) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := userRpc.NewUserRpcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
