// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type SearchRequest struct {
	OrderID string `form:orderID`
}

type SearchResponse struct {
	Message  string `json:"message"`
	OrderID  string `json:orderID`
	Status   int    `json:status`
	Username string `json:username`
}
